# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExcelSupportApp(object):
    def setupUi(self, ExcelSupportApp):
        ExcelSupportApp.setObjectName("ExcelSupportApp")
        ExcelSupportApp.resize(720, 373)
        self.centralwidget = QtWidgets.QWidget(ExcelSupportApp)
        self.centralwidget.setObjectName("centralwidget")
        self.JCname_blank = QtWidgets.QLineEdit(self.centralwidget)
        self.JCname_blank.setGeometry(QtCore.QRect(310, 70, 131, 31))
        self.JCname_blank.setObjectName("JCname_blank")
        self.createfile_button = QtWidgets.QPushButton(self.centralwidget)
        self.createfile_button.setGeometry(QtCore.QRect(460, 70, 81, 31))
        self.createfile_button.setObjectName("createfile_button")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(80, 0, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setObjectName("title")
        self.JClabel = QtWidgets.QLabel(self.centralwidget)
        self.JClabel.setGeometry(QtCore.QRect(190, 70, 121, 31))
        self.JClabel.setObjectName("JClabel")
        self.deletedatabase_button = QtWidgets.QPushButton(self.centralwidget)
        self.deletedatabase_button.setGeometry(QtCore.QRect(40, 70, 101, 31))
        self.deletedatabase_button.setObjectName("deletedatabase_button")
        self.copyfile_button = QtWidgets.QPushButton(self.centralwidget)
        self.copyfile_button.setGeometry(QtCore.QRect(310, 110, 231, 41))
        self.copyfile_button.setObjectName("copyfile_button")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(550, 10, 161, 31))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\U-1TL8FV2\\Downloads\\AOI_Machine_pythonapp\\LogoSonion.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.Alarm_Info = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Alarm_Info.setGeometry(QtCore.QRect(10, 170, 621, 161))
        self.Alarm_Info.setDocumentTitle("")
        self.Alarm_Info.setObjectName("Alarm_Info")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(640, 250, 75, 41))
        self.reset_button.setObjectName("reset_button")
        ExcelSupportApp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExcelSupportApp)
        self.statusbar.setObjectName("statusbar")
        ExcelSupportApp.setStatusBar(self.statusbar)

        self.retranslateUi(ExcelSupportApp)
        QtCore.QMetaObject.connectSlotsByName(ExcelSupportApp)

    def retranslateUi(self, ExcelSupportApp):
        _translate = QtCore.QCoreApplication.translate
        ExcelSupportApp.setWindowTitle(_translate("ExcelSupportApp", "ExcelSupportApp"))
        self.createfile_button.setText(_translate("ExcelSupportApp", "CREATE FILE"))
        self.title.setText(_translate("ExcelSupportApp", "AOI MACHINE - EXCEL INPUT INFORMATION"))
        self.JClabel.setText(_translate("ExcelSupportApp", "Input JC Number"))
        self.deletedatabase_button.setText(_translate("ExcelSupportApp", "Delete Database"))
        self.copyfile_button.setText(_translate("ExcelSupportApp", "FINAL RESULT"))
        self.Alarm_Info.setPlainText(_translate("ExcelSupportApp", "ALARM AREA !!! CALL DEVELOPER IF ANY ERROR HAPPENED"))
        self.reset_button.setText(_translate("ExcelSupportApp", "Reset"))
# import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExcelSupportApp = QtWidgets.QMainWindow()
    ui = Ui_ExcelSupportApp()
    ui.setupUi(ExcelSupportApp)
    ExcelSupportApp.show()
    sys.exit(app.exec_())
